blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/wattero/Software-Testing-Phase-2#readme
    about: Check our README for documentation and setup instructions
